CONSTRUCT {_QUADMODE_
    GRAPH ?c {?s ?p ?o}.
}
WITH {
    SELECT DISTINCT ?c ?s ?p ?o {
#        {
                BIND ($path AS ?s).
                GRAPH ?c{ ?s ?p ?o}.
#        }UNION{
#                BIND ($path AS ?s).
#                ?s (owl:sameAs|^owl:sameAs)* ?same.
#                GRAPH ?c{ ?same ?p ?o}.
#        }
        FILTER (?p != <http://metaservice.org/ns/metaservice#dummy>).
    }
} AS %level1

WITH {
    SELECT (?c2 as ?c) (?x as ?s) (?p2 as ?p)(?o2 as ?o)  {
        SELECT DISTINCT ?c2 ?p2 (?o as ?x) ?o2{
#           {
                INCLUDE %level1filtered.
                GRAPH ?c2{ ?o ?p2 ?o2}.
#           }UNION{
#                INCLUDE %level1filtered.
#                ?o (owl:sameAs|^owl:sameAs)* ?same.
#                GRAPH ?c2{ ?same ?p2 ?o2}.
#            }
            FILTER (?p2 != <http://metaservice.org/ns/metaservice#dummy>).
        }
    }
} AS %level2

WITH {
    SELECT (?c2 as ?c) (?x as ?s) (?p2 as ?p)(?o2 as ?o)  {
        SELECT DISTINCT ?c2 ?p2 (?o as ?x) ?o2{
#            {
                INCLUDE %level2filtered.
                GRAPH ?c2{ ?o ?p2 ?o2}.
#            }UNION{
#                INCLUDE %level2filtered.
#                ?o (owl:sameAs|^owl:sameAs)* ?same.
#                GRAPH ?c2{ ?same ?p2 ?o2}.
#            }
            FILTER (?p2 != <http://metaservice.org/ns/metaservice#dummy>).
        }
    }
} AS %level3

WITH {
    SELECT (max(?time) as ?maxTime) ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level1.
        ?c <http://metaservice.org/ns/metaservice#action> ?action.
        ?c <http://metaservice.org/ns/metaservice#time> ?time.
        ?c <http://metaservice.org/ns/metaservice#path> ?path.
        FILTER( ?time < $selectedTime)
        FILTER( ?action != <http://metaservice.org/ns/metaservice#ActionContinuous> )
    } GROUP BY ?s ?p ?o ?path
} AS %level1max

WITH {
    SELECT (max(?time) as ?maxTime) ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level2.
        ?c <http://metaservice.org/ns/metaservice#action> ?action.
        ?c <http://metaservice.org/ns/metaservice#time> ?time.
        ?c <http://metaservice.org/ns/metaservice#path> ?path.
        FILTER( ?time < $selectedTime)
        FILTER( ?action != <http://metaservice.org/ns/metaservice#ActionContinuous> )
    } GROUP BY ?s ?p ?o ?path
} AS %level2max

WITH {
    SELECT (max(?time) as ?maxTime) ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level3.
        ?c <http://metaservice.org/ns/metaservice#action> ?action.
        ?c <http://metaservice.org/ns/metaservice#time> ?time.
        ?c <http://metaservice.org/ns/metaservice#path> ?path.
        FILTER( ?time < $selectedTime)
        FILTER( ?action != <http://metaservice.org/ns/metaservice#ActionContinuous> )
    }GROUP BY ?s ?p ?o ?path
} AS %level3max

WITH {
    SELECT ?c ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level1.
        ?c <http://metaservice.org/ns/metaservice#action>  <http://metaservice.org/ns/metaservice#ActionContinuous>.
        ?c <http://metaservice.org/ns/metaservice#latest> $selectedTime.
    }
} AS %level1maxContinuous

WITH {
    SELECT ?c ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level2.
        ?c <http://metaservice.org/ns/metaservice#action>  <http://metaservice.org/ns/metaservice#ActionContinuous>.
        ?c <http://metaservice.org/ns/metaservice#latest> $selectedTime.
    }
} AS %level2maxContinuous

WITH {
    SELECT ?c ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level3.
        ?c <http://metaservice.org/ns/metaservice#action>  <http://metaservice.org/ns/metaservice#ActionContinuous>.
        ?c <http://metaservice.org/ns/metaservice#latest> $selectedTime.
    }
} AS %level3maxContinuous

WITH {
    SELECT DISTINCT ?c ?s ?p ?o {{
            hint:Query hint:optimizer "None" .
            INCLUDE %level1.
            ?c <http://metaservice.org/ns/metaservice#action>  <http://metaservice.org/ns/metaservice#ActionAdd>.
            ?c <http://metaservice.org/ns/metaservice#time> ?maxTime.
            INCLUDE %level1max.
        }UNION{
            INCLUDE %level1maxContinuous.
        }
    }
} AS %level1filtered

WITH {
    SELECT DISTINCT ?c ?s ?p ?o {{
            hint:Query hint:optimizer "None" .
            INCLUDE %level2.
            ?c <http://metaservice.org/ns/metaservice#action>  <http://metaservice.org/ns/metaservice#ActionAdd>.
            ?c <http://metaservice.org/ns/metaservice#time> ?maxTime.
            INCLUDE %level2max.
        }UNION{
            INCLUDE %level2maxContinuous.
        }
    }
} AS %level2filtered

WITH {
    SELECT DISTINCT ?c ?s ?p ?o {{
            hint:Query hint:optimizer "None" .
            INCLUDE %level3.
            ?c <http://metaservice.org/ns/metaservice#action>  <http://metaservice.org/ns/metaservice#ActionAdd>.
            ?c <http://metaservice.org/ns/metaservice#time> ?maxTime.
            INCLUDE %level3max.
        }UNION{
            INCLUDE %level3maxContinuous.
        }
    }
} AS %level3filtered

WHERE{
    SELECT DISTINCT ?s ?p ?o{
        {
           INCLUDE %level1filtered
        } UNION {
           INCLUDE %level2filtered
        } UNION {
           INCLUDE %level3filtered
        }
    } ORDER BY ?s ?p ?o
}
