SELECT DISTINCT ?time
WITH {
    SELECT DISTINCT ?c ?o {
        BIND ($path AS ?s).
        GRAPH ?c{ ?s ?p ?o}.
    }
} AS %level1

WITH {
    SELECT (?c2 as ?c) (?o2 as ?o)  {
        SELECT DISTINCT ?c2 ?o2{
            INCLUDE %level1.
            GRAPH ?c2{ ?o ?p2 ?o2}.
        }
    }
} AS %level2

WITH {
    SELECT (?c2 as ?c) (?o2 as ?o)  {
        SELECT DISTINCT ?c2 ?o2{
            INCLUDE %level2.
            GRAPH ?c2{ ?o ?p2 ?o2}.
        }
    }
} AS %level3
WHERE {
    hint:Query hint:optimizer "None" .
    {
        INCLUDE %level1
    } UNION {
        INCLUDE %level2
    } UNION {
        INCLUDE %level3
    }
    ?c ms:dataTime ?time.
    FILTER(?time != 0)
}
ORDER BY DESC(?time)