CONSTRUCT {_QUADMODE_
    GRAPH <http://metaservice.org/ns/metaservice#combinedGraph> {?sr ?pr ?or}.
    GRAPH ?c {?s ?p ?o}.
}
WITH {
    SELECT DISTINCT ?c ?s ?p ?o {
        BIND ($path AS ?s).
        GRAPH ?c{ ?s ?p ?o}.
        FILTER (?p != <http://metaservice.org/ns/metaservice#dummy>).
    }
} AS %level1

WITH {
    SELECT (?c2 as ?c) (?x as ?s) (?p2 as ?p)(?o2 as ?o)  {
        SELECT DISTINCT ?c2 ?p2 (?o as ?x) ?o2{
            INCLUDE %level1filtered.
            GRAPH ?c2{ ?o ?p2 ?o2}.
            FILTER (?p2 != ms:dummy).
        }
    }
} AS %level2

WITH {
    SELECT (?c2 as ?c) (?x as ?s) (?p2 as ?p)(?o2 as ?o)  {
        SELECT DISTINCT ?c2 ?p2 (?o as ?x) ?o2{
            INCLUDE %level2filtered.
            GRAPH ?c2{ ?o ?p2 ?o2}.
            FILTER (?p2 != ms:dummy).
        }
    }
} AS %level3

WITH {
    SELECT (max(?time) as ?maxTime) ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level1.
        ?c a ?type.
        ?c ms:dataTime ?time.
        ?c ms:path ?path.
        FILTER( ?time < $selectedTime)
        FILTER( ?type = ms:AddObservation || ?type = ms:RemoveObservation )
    } GROUP BY ?s ?p ?o ?path
} AS %level1max

WITH {
    SELECT (max(?time) as ?maxTime) ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level2.
        ?c a ?type.
        ?c ms:dataTime ?time.
        ?c ms:path ?path.
        FILTER( ?time < $selectedTime)
        FILTER( ?type = ms:AddObservation || ?type = ms:RemoveObservation )
    } GROUP BY ?s ?p ?o ?path
} AS %level2max

WITH {
    SELECT (max(?time) as ?maxTime) ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level3.
        ?c a ?type.
        ?c ms:dataTime ?time.
        ?c ms:path ?path.
        FILTER( ?time < $selectedTime)
        FILTER( ?type = ms:AddObservation || ?type = ms:RemoveObservation )
    }GROUP BY ?s ?p ?o ?path
} AS %level3max

WITH {
    SELECT ?c ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level1.
        ?c a ms:ContinuousObservation.
        ?c ms:latest $selectedTime.
    }
} AS %level1maxContinuous

WITH {
    SELECT ?c ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level2.
        ?c a ms:ContinuousObservation.
        ?c ms:latest $selectedTime.
    }
} AS %level2maxContinuous

WITH {
    SELECT ?c ?s ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %level3.
        ?c a ms:ContinuousObservation.
        ?c ms:latest $selectedTime.
    }
} AS %level3maxContinuous

WITH {
    SELECT DISTINCT ?c ?s ?p ?o {{
            hint:Query hint:optimizer "None" .
            INCLUDE %level1.
            ?c a ms:AddObservation.
            ?c ms:dataTime ?maxTime.
            INCLUDE %level1max.
        }UNION{
            INCLUDE %level1maxContinuous.
        }
    }
} AS %level1filtered

WITH {
    SELECT DISTINCT ?c ?s ?p ?o {{
            hint:Query hint:optimizer "None" .
            INCLUDE %level2.
            ?c a ms:AddObservation.
            ?c ms:dataTime ?maxTime.
            INCLUDE %level2max.
        }UNION{
            INCLUDE %level2maxContinuous.
        }
    }
} AS %level2filtered

WITH {
    SELECT DISTINCT ?c ?s ?p ?o {{
            hint:Query hint:optimizer "None" .
            INCLUDE %level3.
            ?c a ms:AddObservation.
            ?c ms:dataTime ?maxTime.
            INCLUDE %level3max.
        }UNION{
            INCLUDE %level3maxContinuous.
        }
    }
} AS %level3filtered

WITH {
    SELECT DISTINCT ?c ?s ?p ?o{
        {
           INCLUDE %level1filtered
        } UNION {
           INCLUDE %level2filtered
        } UNION {
           INCLUDE %level3filtered
        }
    }
} AS %statements

WITH {
    SELECT DISTINCT (?s as ?sr) (?p as ?pr) (?o as ?or){
        INCLUDE %statements
    }
} AS %unionstatements

WITH{
    SELECT DISTINCT ?c{
       INCLUDE %statements
    }
} AS %contexts

WITH {
    SELECT ?c (?c as ?s) ?p ?o{
        hint:Query hint:optimizer "None" .
        INCLUDE %contexts
        GRAPH ?c {?c ?p ?o}.
    }
} AS %contextstatements


WHERE{
    {
        INCLUDE %unionstatements
    } UNION {
        INCLUDE %statements
    } UNION {
        INCLUDE %contextstatements
    }
}
