CONSTRUCT {_QUADMODE_
    GRAPH ?graph1 {$path ?relation1 ?value1}.
    GRAPH ?ggraph1 {?graph1 ?grelation1 ?gvalue1}.
    GRAPH ?graph2 { ?value1 ?relation2 ?value2}.
    GRAPH ?ggraph2 {?graph2 ?grelation2 ?gvalue2}.
    GRAPH ?graph3 { ?value2 <dc:description> ?value3}.

}
WHERE{
    {
        SELECT DISTINCT ?graph1 ?relation1 ?value1 {
            GRAPH ?graph1 { $path ?relation1   ?value1}.
            FILTER (?relation1 != <http://metaservice.org/ns/metaservice#dummy>).
            OPTIONAL {
                GRAPH ?ggraph1 { ?graph1 ?grelation1 ?gvalue1.}
            }
        }
    }.
    OPTIONAL {
        GRAPH ?graph2 { ?value1 ?relation2 ?value2}.
        FILTER (?relation2 != <http://metaservice.org/ns/metaservice#dummy>).
        OPTIONAL {
            GRAPH ?ggraph2 {?graph2 ?grelation2 ?gvalue2.}
        }
        OPTIONAL {
              GRAPH ?graph3 { ?value2 <dc:description> ?value3}.
        }
    }
}