SELECT *
WITH
{
  SELECT DISTINCT
 ?subject ?title ?type ?relevance
 WHERE {
  ?title bds:search $q ;
         bds:relevance  ?relevance .
  ?subject a ?type;
           rdfs:label ?title
               FILTER (
         ?type = <http://purl.org/adms/sw/SoftwareProject>
         ||
         ?type = <http://purl.org/adms/sw/SoftwareRelease>
         ||
         ?type = <http://purl.org/adms/sw/SoftwarePackage>
         ||
         ?type = <http://metaservice.org/ns/cve#CVE>
         ||
         ?type = <http://metaservice.org/ns/cpe#CPE>
     )
} ORDER BY DESC(?relevance) ?title
} AS %result

WHERE{
  INCLUDE %result.
}
 LIMIT $limit
 OFFSET $offset